apiVersion: v1
kind: Service
metadata:
  name: opensearch-exporter
  labels:
    app: opensearch-exporter
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: opensearch-exporter
  type: ClusterIP